### ISSUE TITLE
Loading Spinner Overstays it's Welcome

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/sbplus#57] opened 2015-07-30 21:00 UTC
Many times a slide will load very fast, and the loading spinner will stay around afterwards. In my opinion this is both misleading (it already loaded!) and visual clutter / noise.

Would it be possible to take the event that fires to start the fade in of the slide to *also* hide the spinner from view? That would be fantastic.

~~An alternate method might be to place the spinner on a layer below the slide's layer so that when it does fade in, it fades in on top of the spinner, making it go away as soon as the image is there. This technique would provide a smooth transition too.~~

~~Either method would be great.~~ Thanks!

**Note:** A similar thing should be done for the video spinner.

**Comment by Lin87** [comment] 2015-07-31 17:20
I cannot reproduce this issue. Please clarify with screen capture if possible. Note: I cannot remove loading spinner in the video. It its part of the VideoJS library. I can however make our loading spinner to look like somewhat similar to VideoJS's spinner. Also, no other spinner was used when slide is a video.

**Comment by Lin87** [comment] 2015-08-03 22:18
Still cannot reproduce this issue. Please provide more info when you have time.

**Comment by owlboy** [comment] 2015-11-25 21:20
I finally have a chance / remembered to clarify!

This video should clear things up: https://youtu.be/cuMd14ho-eI

**Comment by Lin87** [comment] 2016-04-11 21:01
Adjusted. Done. Enhanced. Will be released in version 2.8.0. along with all of the ADA stuffs.

**Closed by Lin87** 2016-04-11 21:01 UTC
Labels: enhancement, need-more-info
